import type { Photography } from "@/types";

/**
 * Photographs ingested from the Metropolitan Museum of Art Open Access API.
 * Each photo's ResonanceAxes derives from emotion-keyword matching on its tags.
 * Generated by scripts/ingest-met-photo.mjs.
 *
 * Total: 61 photographs.
 */
export const PHOTOGRAPHS_MET: Photography[] = [
  {
    "id": "met-photo-302375",
    "title": "[Union Private, Eleventh New York Infantry (First Fire Zouaves)]",
    "photographer": "Unknown",
    "year": "May–June 1861",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP272311.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/302375",
    "emotionResonance": [
      "miedo",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "soldiers",
      "american civil war",
      "men",
      "portraits"
    ],
    "resonance": {
      "energy": 62,
      "temperature": 45,
      "tension": 57,
      "density": 52,
      "movement": 48,
      "temporality": 42,
      "humanity": 83,
      "clarity": 54,
      "intimacy": 50,
      "control": 30
    },
    "description": "Purchase, Harris Brisbane Dick Fund, by exchange, 2022",
    "poeticDescription": "[Union Private, Eleventh New York Infantry (First Fire Zouaves)]"
  },
  {
    "id": "met-photo-285964",
    "title": "[Patient, Surrey County Lunatic Asylum]",
    "photographer": "Hugh Welch Diamond",
    "year": "1850–55",
    "culture": "British",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP261078.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/285964",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "portraits",
      "women"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Gilman Collection, Purchase, Anonymous Gifts, by exchange, 2005",
    "poeticDescription": "[Patient, Surrey County Lunatic Asylum]"
  },
  {
    "id": "met-photo-261937",
    "title": "Brig on the Water",
    "photographer": "Gustave Le Gray",
    "year": "1856",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP240624.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/261937",
    "emotionResonance": [
      "melancolía"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "seascapes",
      "clouds",
      "boats"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 40,
      "tension": 55,
      "density": 60,
      "movement": 15,
      "temporality": 90,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 75,
      "control": 40
    },
    "description": "Gift of A. Hyatt Mayor, 1976",
    "poeticDescription": "Brig on the Water"
  },
  {
    "id": "met-photo-288089",
    "title": "[Spreading Oak with Seated Figure]",
    "photographer": "Unknown",
    "year": "1850s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP145375.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/288089",
    "emotionResonance": [
      "soledad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "oaks",
      "trees"
    ],
    "resonance": {
      "energy": 18,
      "temperature": 38,
      "tension": 40,
      "density": 48,
      "movement": 12,
      "temporality": 80,
      "humanity": 72,
      "clarity": 55,
      "intimacy": 30,
      "control": 60
    },
    "description": "Gift of Hans P. Kraus Jr., 2007",
    "poeticDescription": "[Spreading Oak with Seated Figure]"
  },
  {
    "id": "met-photo-285922",
    "title": "[Wild Fennel]",
    "photographer": "William Henry Fox Talbot",
    "year": "1841–42",
    "culture": "British",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP143014.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/285922",
    "emotionResonance": [
      "soledad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "plants"
    ],
    "resonance": {
      "energy": 18,
      "temperature": 38,
      "tension": 40,
      "density": 48,
      "movement": 12,
      "temporality": 80,
      "humanity": 72,
      "clarity": 55,
      "intimacy": 30,
      "control": 60
    },
    "description": "Gilman Collection, Purchase, Denise and Andrew Saul Gift, 2005",
    "poeticDescription": "[Wild Fennel]"
  },
  {
    "id": "met-photo-287727",
    "title": "The Colosseum",
    "photographer": "Jane Martha St. John",
    "year": "1856",
    "culture": "British",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP143536.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/287727",
    "emotionResonance": [
      "soledad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "architecture",
      "ruins"
    ],
    "resonance": {
      "energy": 18,
      "temperature": 38,
      "tension": 40,
      "density": 48,
      "movement": 12,
      "temporality": 80,
      "humanity": 72,
      "clarity": 55,
      "intimacy": 30,
      "control": 60
    },
    "description": "Gilman Collection, Gift of The Howard Gilman Foundation, 2005",
    "poeticDescription": "The Colosseum"
  },
  {
    "id": "met-photo-266902",
    "title": "Gioacchino Rossini",
    "photographer": "Nadar",
    "year": "March 1856",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT7047.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/266902",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "portraits"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Purchase, Marie-Thérèse and André Jammes and Annalee Newman Gifts, The Horace W. Goldsmith Foundation Gift through Joyce and Robert Menschel, and Nancy and Edwin Marks Gift, 1993",
    "poeticDescription": "Gioacchino Rossini"
  },
  {
    "id": "met-photo-301993",
    "title": "[Major General William Tecumseh Sherman Wearing Mourning Armband]",
    "photographer": "Brady & Co.",
    "year": "1865",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP265105.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/301993",
    "emotionResonance": [
      "tristeza",
      "miedo",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "american civil war",
      "men",
      "portraits",
      "generals"
    ],
    "resonance": {
      "energy": 49,
      "temperature": 42,
      "tension": 53,
      "density": 54,
      "movement": 38,
      "temporality": 52,
      "humanity": 84,
      "clarity": 49,
      "intimacy": 57,
      "control": 34
    },
    "description": "Purchase, Alfred Stieglitz Society Gifts, 2013",
    "poeticDescription": "[Major General William Tecumseh Sherman Wearing Mourning Armband]"
  },
  {
    "id": "met-photo-268314",
    "title": "[Elderly Woman in Black Cape and Bonnet with Mourning Crape]",
    "photographer": "Southworth and Hawes",
    "year": "ca. 1850",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/37.14.17.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/268314",
    "emotionResonance": [
      "tristeza",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "portraits",
      "women"
    ],
    "resonance": {
      "energy": 37,
      "temperature": 49,
      "tension": 37,
      "density": 50,
      "movement": 28,
      "temporality": 65,
      "humanity": 84,
      "clarity": 56,
      "intimacy": 63,
      "control": 47
    },
    "description": "Gift of I. N. Phelps Stokes, Edward S. Hawes, Alice Mary Hawes, and Marion Augusta Hawes, 1937",
    "poeticDescription": "[Elderly Woman in Black Cape and Bonnet with Mourning Crape]"
  },
  {
    "id": "met-photo-271509",
    "title": "[Carte-de-Visite Album of British and European Royalty]",
    "photographer": "F. Joubert",
    "year": "1860s–70s",
    "culture": "British",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP333840.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/271509",
    "emotionResonance": [
      "ternura",
      "alegría",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "children",
      "men",
      "portraits",
      "women"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 71,
      "tension": 19,
      "density": 38,
      "movement": 48,
      "temporality": 56,
      "humanity": 86,
      "clarity": 73,
      "intimacy": 71,
      "control": 57
    },
    "description": "The Elisha Whittelsey Collection, The Elisha Whittelsey Fund, 1969",
    "poeticDescription": "[Carte-de-Visite Album of British and European Royalty]"
  },
  {
    "id": "met-photo-301949",
    "title": "[Mourning Corsage with Portrait of Abraham Lincoln]",
    "photographer": "Unknown",
    "year": "April 1865",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP265006.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/301949",
    "emotionResonance": [
      "tristeza",
      "miedo",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "american civil war",
      "abraham lincoln",
      "portraits"
    ],
    "resonance": {
      "energy": 49,
      "temperature": 42,
      "tension": 53,
      "density": 54,
      "movement": 38,
      "temporality": 52,
      "humanity": 84,
      "clarity": 49,
      "intimacy": 57,
      "control": 34
    },
    "description": "Purchase, Alfred Stieglitz Society Gifts, 2013",
    "poeticDescription": "[Mourning Corsage with Portrait of Abraham Lincoln]"
  },
  {
    "id": "met-photo-268432",
    "title": "Newhaven Family",
    "photographer": "Hill and Adamson",
    "year": "1843–47",
    "culture": "British, Scottish",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP140489.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/268432",
    "emotionResonance": [
      "nostalgia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "women",
      "family"
    ],
    "resonance": {
      "energy": 28,
      "temperature": 55,
      "tension": 42,
      "density": 55,
      "movement": 20,
      "temporality": 95,
      "humanity": 90,
      "clarity": 45,
      "intimacy": 80,
      "control": 38
    },
    "description": "Harris Brisbane Dick Fund, 1937",
    "poeticDescription": "Newhaven Family"
  },
  {
    "id": "met-photo-289328",
    "title": "Mandarin with Family",
    "photographer": "Milton M. Miller",
    "year": "1860–1863",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP165608.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/289328",
    "emotionResonance": [
      "nostalgia",
      "ternura",
      "alegría",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "children",
      "girls",
      "men",
      "portraits",
      "women"
    ],
    "resonance": {
      "energy": 46,
      "temperature": 67,
      "tension": 25,
      "density": 43,
      "movement": 41,
      "temporality": 66,
      "humanity": 87,
      "clarity": 66,
      "intimacy": 73,
      "control": 53
    },
    "description": "Gilman Collection, Purchase, Robert Rosenkranz Gift, 2005",
    "poeticDescription": "Mandarin with Family"
  },
  {
    "id": "met-photo-283176",
    "title": "[Hutchinson Family Singers]",
    "photographer": "Unknown",
    "year": "1845",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT5679.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/283176",
    "emotionResonance": [
      "nostalgia",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "portraits"
    ],
    "resonance": {
      "energy": 40,
      "temperature": 59,
      "tension": 35,
      "density": 49,
      "movement": 29,
      "temporality": 77,
      "humanity": 85,
      "clarity": 59,
      "intimacy": 68,
      "control": 45
    },
    "description": "Gilman Collection, Gift of The Howard Gilman Foundation, 2005",
    "poeticDescription": "[Hutchinson Family Singers]"
  },
  {
    "id": "met-photo-306227",
    "title": "The Adamson Family",
    "photographer": "Hill and Adamson",
    "year": "1843–1847",
    "culture": "British, Scottish",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP703133.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/306227",
    "emotionResonance": [
      "nostalgia"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 28,
      "temperature": 55,
      "tension": 42,
      "density": 55,
      "movement": 20,
      "temporality": 95,
      "humanity": 90,
      "clarity": 45,
      "intimacy": 80,
      "control": 38
    },
    "description": "Bequest of Maurice B. Sendak, 2012",
    "poeticDescription": "The Adamson Family"
  },
  {
    "id": "met-photo-271912",
    "title": "The Floods of 1856, Avignon",
    "photographer": "Edouard Baldus",
    "year": "1856",
    "culture": "French, born Prussia",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP109596.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/271912",
    "emotionResonance": [
      "serenidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "landscapes",
      "floods"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 52,
      "tension": 10,
      "density": 30,
      "movement": 12,
      "temporality": 75,
      "humanity": 70,
      "clarity": 85,
      "intimacy": 60,
      "control": 82
    },
    "description": "Purchase, Robert Hurst, Paul F. Walter and Anonymous Gifts; Harris Brisbane Dick Fund, Rogers Fund and Gift of Mrs. Claire K. Feins, in memory of Daniel M. Feins and Linda S. Silverman, by exchange; and funds from various donors, 1997",
    "poeticDescription": "The Floods of 1856, Avignon"
  },
  {
    "id": "met-photo-283140",
    "title": "[Carlotta Cortudino]",
    "photographer": "Giacomo Caneva",
    "year": "ca. 1852",
    "culture": "Italian",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT204497.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/283140",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "girls",
      "portraits"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Gilman Collection, Purchase, Joseph M. Cohen Gift, 2005",
    "poeticDescription": "[Carlotta Cortudino]"
  },
  {
    "id": "met-photo-283077",
    "title": "[Trees]",
    "photographer": "Thomas Keith",
    "year": "1854–57",
    "culture": "British, Scottish",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP143008.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/283077",
    "emotionResonance": [
      "amor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "trees"
    ],
    "resonance": {
      "energy": 55,
      "temperature": 75,
      "tension": 38,
      "density": 55,
      "movement": 45,
      "temporality": 60,
      "humanity": 98,
      "clarity": 50,
      "intimacy": 95,
      "control": 40
    },
    "description": "Gilman Collection, Purchase, Harriette and Noel Levine Gift, 2005",
    "poeticDescription": "[Trees]"
  },
  {
    "id": "met-photo-264960",
    "title": "Mother of the Forest",
    "photographer": "Carleton E. Watkins",
    "year": "1865–66, printed ca. 1876",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP152241.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/264960",
    "emotionResonance": [
      "ternura"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "forests",
      "trees"
    ],
    "resonance": {
      "energy": 28,
      "temperature": 72,
      "tension": 10,
      "density": 38,
      "movement": 25,
      "temporality": 65,
      "humanity": 96,
      "clarity": 68,
      "intimacy": 92,
      "control": 65
    },
    "description": "Gift of Carole and Irwin Lainoff, Ruth P. Lasser and Joseph R. Lasser, Mr. and Mrs. John T. Marvin, Martin E. and Joan Messinger, Richard L. Yett and Sheri and Paul Siegel, 1986",
    "poeticDescription": "Mother of the Forest"
  },
  {
    "id": "met-photo-732750",
    "title": "The Mother of the Forest - Calaveras Grove",
    "photographer": "Carleton E. Watkins",
    "year": "ca. 1878",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP136789.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/732750",
    "emotionResonance": [
      "ternura"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "forests",
      "trees"
    ],
    "resonance": {
      "energy": 28,
      "temperature": 72,
      "tension": 10,
      "density": 38,
      "movement": 25,
      "temporality": 65,
      "humanity": 96,
      "clarity": 68,
      "intimacy": 92,
      "control": 65
    },
    "description": "Gilman Collection, Gift of The Howard Gilman Foundation, 2005",
    "poeticDescription": "The Mother of the Forest - Calaveras Grove"
  },
  {
    "id": "met-photo-261590",
    "title": "The Far East: A Monthly Journal, Illustrated with Photographs",
    "photographer": "William Thomas Saunders",
    "year": "1870s",
    "culture": "British",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP295719.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/261590",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "portraits"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Gift of John J. McKendry, 1975",
    "poeticDescription": "The Far East: A Monthly Journal, Illustrated with Photographs"
  },
  {
    "id": "met-photo-264577",
    "title": "Javanese Child",
    "photographer": "Unknown",
    "year": "1860s–70s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP71290.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/264577",
    "emotionResonance": [
      "ternura",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "girls",
      "portraits"
    ],
    "resonance": {
      "energy": 40,
      "temperature": 67,
      "tension": 19,
      "density": 40,
      "movement": 32,
      "temporality": 62,
      "humanity": 88,
      "clarity": 70,
      "intimacy": 74,
      "control": 59
    },
    "description": "Gift of Matthew Dontzin, 1985",
    "poeticDescription": "Javanese Child"
  },
  {
    "id": "met-photo-726481",
    "title": "Damascus Gate, Jerusalem (208. Atlit. Syrie Chapelle. [sic])",
    "photographer": "Joseph-Philibert Girault de Prangey",
    "year": "1844",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP-13897-037.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/726481",
    "emotionResonance": [
      "miedo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "architecture",
      "gates"
    ],
    "resonance": {
      "energy": 72,
      "temperature": 28,
      "tension": 85,
      "density": 62,
      "movement": 58,
      "temporality": 25,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 45,
      "control": 8
    },
    "description": "Purchase, Mr. and Mrs. John A. Moran Gift, in memory of Louise Chisholm Moran, Joyce F. Menschel Gift, Joseph Pulitzer Bequest, 2016 Benefit Fund, and Gift of Dr. Mortimer D. Sackler, Theresa Sackler and Family, 2016 (2016.610)",
    "poeticDescription": "Damascus Gate, Jerusalem (208. Atlit. Syrie Chapelle. [sic])"
  },
  {
    "id": "met-photo-726483",
    "title": "Aleppo, Viewed from the Antioch Gate (252. Alep. 1844. Prise de Bab Antakieh. (publiée))",
    "photographer": "Joseph-Philibert Girault de Prangey",
    "year": "1844",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP-13897-041.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/726483",
    "emotionResonance": [
      "miedo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "architecture",
      "ruins"
    ],
    "resonance": {
      "energy": 72,
      "temperature": 28,
      "tension": 85,
      "density": 62,
      "movement": 58,
      "temporality": 25,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 45,
      "control": 8
    },
    "description": "Purchase, Mr. and Mrs. John A. Moran Gift, in memory of Louise Chisholm Moran, Joyce F. Menschel Gift, Joseph Pulitzer Bequest, 2016 Benefit Fund, and Gift of Dr. Mortimer D. Sackler, Theresa Sackler and Family, 2016 (2016.612)",
    "poeticDescription": "Aleppo, Viewed from the Antioch Gate (252. Alep. 1844. Prise de Bab Antakieh. (publiée))"
  },
  {
    "id": "met-photo-711655",
    "title": "[Civil War View]",
    "photographer": "Thomas C. Roche",
    "year": "1860s",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP248318.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/711655",
    "emotionResonance": [
      "miedo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buildings",
      "american civil war"
    ],
    "resonance": {
      "energy": 72,
      "temperature": 28,
      "tension": 85,
      "density": 62,
      "movement": 58,
      "temporality": 25,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 45,
      "control": 8
    },
    "description": "Gilman Collection, Purchase, The Horace W. Goldsmith Foundation Gift, through Joyce and Robert Menschel, 2005",
    "poeticDescription": "[Civil War View]"
  },
  {
    "id": "met-photo-711643",
    "title": "[Civil War View]",
    "photographer": "Thomas C. Roche",
    "year": "1860s",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP248306.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/711643",
    "emotionResonance": [
      "miedo",
      "serenidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "american civil war",
      "landscapes"
    ],
    "resonance": {
      "energy": 46,
      "temperature": 40,
      "tension": 48,
      "density": 46,
      "movement": 35,
      "temporality": 50,
      "humanity": 78,
      "clarity": 60,
      "intimacy": 53,
      "control": 45
    },
    "description": "Gilman Collection, Purchase, The Horace W. Goldsmith Foundation Gift, through Joyce and Robert Menschel, 2005",
    "poeticDescription": "[Civil War View]"
  },
  {
    "id": "met-photo-286348",
    "title": "[Three Planters]",
    "photographer": "Unknown",
    "year": "after 1845",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP338158.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/286348",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "portraits"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Gilman Collection, Purchase, Ann Tenenbaum and Thomas H. Lee Gift, 2005",
    "poeticDescription": "[Three Planters]"
  },
  {
    "id": "met-photo-282051",
    "title": "[Two Standing Female Nudes]",
    "photographer": "Félix-Jacques-Antoine Moulin",
    "year": "ca. 1850",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT1154.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/282051",
    "emotionResonance": [
      "admiración",
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "portraits",
      "female nudes"
    ],
    "resonance": {
      "energy": 44,
      "temperature": 55,
      "tension": 50,
      "density": 50,
      "movement": 28,
      "temporality": 58,
      "humanity": 81,
      "clarity": 52,
      "intimacy": 54,
      "control": 42
    },
    "description": "The Rubel Collection, Purchase, Anonymous Gift and Lila Acheson Wallace Gift, 1997",
    "poeticDescription": "[Two Standing Female Nudes]"
  },
  {
    "id": "met-photo-282006",
    "title": "The Seine at Rouen",
    "photographer": "William Henry Fox Talbot",
    "year": "May 1843",
    "culture": "British",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP339364.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/282006",
    "emotionResonance": [
      "esperanza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "docks",
      "boats"
    ],
    "resonance": {
      "energy": 48,
      "temperature": 65,
      "tension": 32,
      "density": 28,
      "movement": 42,
      "temporality": 45,
      "humanity": 88,
      "clarity": 68,
      "intimacy": 58,
      "control": 48
    },
    "description": "The Rubel Collection, Purchase, Lila Acheson Wallace and Anonymous Gifts, 1997",
    "poeticDescription": "The Seine at Rouen"
  },
  {
    "id": "met-photo-301944",
    "title": "Corporal Hiram Warner, Company C, Second United States Sharp Shooters",
    "photographer": "Unknown",
    "year": "1861–62",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP265326.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/301944",
    "emotionResonance": [
      "miedo",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "soldiers",
      "american civil war",
      "men",
      "portraits"
    ],
    "resonance": {
      "energy": 62,
      "temperature": 45,
      "tension": 57,
      "density": 52,
      "movement": 48,
      "temporality": 42,
      "humanity": 83,
      "clarity": 54,
      "intimacy": 50,
      "control": 30
    },
    "description": "The Horace W. Goldsmith Foundation Fund, through Joyce and Robert Menschel, 2012",
    "poeticDescription": "Corporal Hiram Warner, Company C, Second United States Sharp Shooters"
  },
  {
    "id": "met-photo-287291",
    "title": "Cañon of Kanab Wash, Looking South",
    "photographer": "William H. Bell",
    "year": "1872",
    "culture": "American, born England",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT244893.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/287291",
    "emotionResonance": [
      "serenidad",
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "mountains",
      "landscapes"
    ],
    "resonance": {
      "energy": 44,
      "temperature": 52,
      "tension": 33,
      "density": 38,
      "movement": 27,
      "temporality": 82,
      "humanity": 63,
      "clarity": 64,
      "intimacy": 44,
      "control": 59
    },
    "description": "Gilman Collection, Purchase, The Horace W. Goldsmith Foundation Gift, through Joyce and Robert Menschel, 2005",
    "poeticDescription": "Cañon of Kanab Wash, Looking South"
  },
  {
    "id": "met-photo-268431",
    "title": "Newhaven Children",
    "photographer": "Hill and Adamson",
    "year": "1843–47",
    "culture": "British, Scottish",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP140488.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/268431",
    "emotionResonance": [
      "ternura",
      "alegría"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "boys",
      "girls"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 75,
      "tension": 15,
      "density": 37,
      "movement": 53,
      "temporality": 55,
      "humanity": 89,
      "clarity": 73,
      "intimacy": 79,
      "control": 60
    },
    "description": "Harris Brisbane Dick Fund, 1937",
    "poeticDescription": "Newhaven Children"
  },
  {
    "id": "met-photo-268477",
    "title": "Finlay Children",
    "photographer": "Hill and Adamson",
    "year": "1843–47",
    "culture": "British, Scottish",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP140530.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/268477",
    "emotionResonance": [
      "ternura",
      "alegría"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "boys",
      "girls"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 75,
      "tension": 15,
      "density": 37,
      "movement": 53,
      "temporality": 55,
      "humanity": 89,
      "clarity": 73,
      "intimacy": 79,
      "control": 60
    },
    "description": "Harris Brisbane Dick Fund, 1937",
    "poeticDescription": "Finlay Children"
  },
  {
    "id": "met-photo-285719",
    "title": "Professor Schneider's Children",
    "photographer": "W. & F. Langenheim",
    "year": "ca. 1842",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP332525.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/285719",
    "emotionResonance": [
      "ternura",
      "alegría",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "boys",
      "girls",
      "portraits"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 71,
      "tension": 19,
      "density": 38,
      "movement": 48,
      "temporality": 56,
      "humanity": 86,
      "clarity": 73,
      "intimacy": 71,
      "control": 57
    },
    "description": "Gilman Collection, Gift of The Howard Gilman Foundation, 2005",
    "poeticDescription": "Professor Schneider's Children"
  },
  {
    "id": "met-photo-306149",
    "title": "Frank, Frederick & Alice. \"The Children of the Battle Field\"",
    "photographer": "Wenderoth, Taylor & Brown",
    "year": "1863",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP274800.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/306149",
    "emotionResonance": [
      "ternura",
      "miedo",
      "alegría",
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "american civil war",
      "boys",
      "girls",
      "portraits"
    ],
    "resonance": {
      "energy": 57,
      "temperature": 60,
      "tension": 36,
      "density": 44,
      "movement": 50,
      "temporality": 48,
      "humanity": 86,
      "clarity": 63,
      "intimacy": 64,
      "control": 45
    },
    "description": "Gift of Eva Kasiska, 1947",
    "poeticDescription": "Frank, Frederick & Alice. \"The Children of the Battle Field\""
  },
  {
    "id": "met-photo-294474",
    "title": "Pine Mountain",
    "photographer": "George N. Barnard",
    "year": "1860s",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP237587.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/294474",
    "emotionResonance": [
      "miedo",
      "serenidad",
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "american civil war",
      "landscapes"
    ],
    "resonance": {
      "energy": 53,
      "temperature": 44,
      "tension": 50,
      "density": 46,
      "movement": 37,
      "temporality": 63,
      "humanity": 70,
      "clarity": 54,
      "intimacy": 44,
      "control": 42
    },
    "description": "Pfeiffer and Rogers Funds, 1970",
    "poeticDescription": "Pine Mountain"
  },
  {
    "id": "met-photo-294459",
    "title": "Lu-La Lake, Lookout Mountain",
    "photographer": "George N. Barnard",
    "year": "1864 or 1866",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP274629.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/294459",
    "emotionResonance": [
      "miedo",
      "serenidad",
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "american civil war",
      "landscapes"
    ],
    "resonance": {
      "energy": 53,
      "temperature": 44,
      "tension": 50,
      "density": 46,
      "movement": 37,
      "temporality": 63,
      "humanity": 70,
      "clarity": 54,
      "intimacy": 44,
      "control": 42
    },
    "description": "Pfeiffer and Rogers Funds, 1970",
    "poeticDescription": "Lu-La Lake, Lookout Mountain"
  },
  {
    "id": "met-photo-263054",
    "title": "[Town on Plain with Mountain in Background]",
    "photographer": "Unknown",
    "year": "1860s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP71196.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/263054",
    "emotionResonance": [
      "serenidad",
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "towns",
      "mountains",
      "landscapes"
    ],
    "resonance": {
      "energy": 44,
      "temperature": 52,
      "tension": 33,
      "density": 38,
      "movement": 27,
      "temporality": 82,
      "humanity": 63,
      "clarity": 64,
      "intimacy": 44,
      "control": 59
    },
    "description": "Gift of Mrs. A. Hyatt Mayor, 1981",
    "poeticDescription": "[Town on Plain with Mountain in Background]"
  },
  {
    "id": "met-photo-289289",
    "title": "Piled Stone Mountain Near Sing Chang",
    "photographer": "Lai Afong",
    "year": "ca. 1869",
    "culture": "Chinese",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP165568.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/289289",
    "emotionResonance": [
      "serenidad",
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "mountains",
      "landscapes"
    ],
    "resonance": {
      "energy": 44,
      "temperature": 52,
      "tension": 33,
      "density": 38,
      "movement": 27,
      "temporality": 82,
      "humanity": 63,
      "clarity": 64,
      "intimacy": 44,
      "control": 59
    },
    "description": "Gilman Collection, Purchase, Robert Rosenkranz Gift, 2005",
    "poeticDescription": "Piled Stone Mountain Near Sing Chang"
  },
  {
    "id": "met-photo-283736",
    "title": "A Street in Grasse",
    "photographer": "Charles Nègre",
    "year": "1852",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT4681.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/283736",
    "emotionResonance": [
      "curiosidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buildings",
      "women"
    ],
    "resonance": {
      "energy": 58,
      "temperature": 60,
      "tension": 38,
      "density": 32,
      "movement": 62,
      "temporality": 42,
      "humanity": 78,
      "clarity": 65,
      "intimacy": 48,
      "control": 55
    },
    "description": "Purchase, Jennifer and Joseph Duke Gift and several members of The Chairman's Council Gifts, 2000",
    "poeticDescription": "A Street in Grasse"
  },
  {
    "id": "met-photo-284453",
    "title": "Street Scene, La-Queue-en-Brie (Val-de-Marne)",
    "photographer": "Edgar Degas",
    "year": "ca. 1896",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP252161.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/284453",
    "emotionResonance": [
      "curiosidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "women",
      "street scene"
    ],
    "resonance": {
      "energy": 58,
      "temperature": 60,
      "tension": 38,
      "density": 32,
      "movement": 62,
      "temporality": 42,
      "humanity": 78,
      "clarity": 65,
      "intimacy": 48,
      "control": 55
    },
    "description": "Gift of Paul F. Walter, 2000",
    "poeticDescription": "Street Scene, La-Queue-en-Brie (Val-de-Marne)"
  },
  {
    "id": "met-photo-299469",
    "title": "[Man in Chainmail Tunic Posing as a Dying Soldier]",
    "photographer": "Adrien Constant de Rebecque",
    "year": "ca. 1863",
    "culture": "Swiss",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP262062.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/299469",
    "emotionResonance": [
      "pasmo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "armor",
      "men"
    ],
    "resonance": {
      "energy": 32,
      "temperature": 52,
      "tension": 28,
      "density": 42,
      "movement": 12,
      "temporality": 28,
      "humanity": 68,
      "clarity": 78,
      "intimacy": 52,
      "control": 58
    },
    "description": "Gilman Collection, Purchase, The Howard Gilman Foundation Gift, 2012",
    "poeticDescription": "[Man in Chainmail Tunic Posing as a Dying Soldier]"
  },
  {
    "id": "met-photo-261516",
    "title": "Convalescente (colorieè)",
    "photographer": "Pierre-Louis Pierson",
    "year": "1861–67",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT249158.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/261516",
    "emotionResonance": [
      "pasmo"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 32,
      "temperature": 52,
      "tension": 28,
      "density": 42,
      "movement": 12,
      "temporality": 28,
      "humanity": 68,
      "clarity": 78,
      "intimacy": 52,
      "control": 58
    },
    "description": "David Hunter McAlpin Fund, 1975",
    "poeticDescription": "Convalescente (colorieè)"
  },
  {
    "id": "met-photo-289070",
    "title": "[Group of Adults and Children on a Village Street in the Auvergne]",
    "photographer": "Felix Thiollier",
    "year": "ca. 1910",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP237971.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/289070",
    "emotionResonance": [
      "ternura",
      "alegría",
      "curiosidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "villages",
      "boys",
      "girls",
      "men",
      "women"
    ],
    "resonance": {
      "energy": 54,
      "temperature": 70,
      "tension": 23,
      "density": 35,
      "movement": 56,
      "temporality": 51,
      "humanity": 85,
      "clarity": 70,
      "intimacy": 68,
      "control": 58
    },
    "description": "Twentieth-Century Photography Fund, 2008",
    "poeticDescription": "[Group of Adults and Children on a Village Street in the Auvergne]"
  },
  {
    "id": "met-photo-291745",
    "title": "[Carte-de-visite Album of Collaged Portraits]",
    "photographer": "Unknown",
    "year": "1850s–90s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP-12672-021.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/291745",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "portraits",
      "women"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Bequest of Herbert Mitchell, 2008",
    "poeticDescription": "[Carte-de-visite Album of Collaged Portraits]"
  },
  {
    "id": "met-photo-286524",
    "title": "Nude",
    "photographer": "Félix-Jacques-Antoine Moulin",
    "year": "ca. 1850",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP275763.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/286524",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "female nudes"
    ],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Gilman Collection, Purchase, The Horace W. Goldsmith Foundation Gift, through Joyce and Robert Menschel, 2005",
    "poeticDescription": "Nude"
  },
  {
    "id": "met-photo-282602",
    "title": "[Female Nude in Studio]",
    "photographer": "Franck-François-Genès Chauvassaignes",
    "year": "1856–59",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT1168.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/282602",
    "emotionResonance": [
      "admiración",
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "portraits",
      "female nudes"
    ],
    "resonance": {
      "energy": 44,
      "temperature": 55,
      "tension": 50,
      "density": 50,
      "movement": 28,
      "temporality": 58,
      "humanity": 81,
      "clarity": 52,
      "intimacy": 54,
      "control": 42
    },
    "description": "Purchase, The Horace W. Goldsmith Foundation Gift, through Joyce and Robert Menschel, 1998",
    "poeticDescription": "[Female Nude in Studio]"
  },
  {
    "id": "met-photo-266982",
    "title": "[Female Nude, Reclining, in Profile]",
    "photographer": "Julien Vallou de Villeneuve",
    "year": "ca. 1853",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DT1157.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/266982",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "female nudes"
    ],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Purchase, Lila Acheson Wallace Gift, 1993",
    "poeticDescription": "[Female Nude, Reclining, in Profile]"
  },
  {
    "id": "met-photo-286803",
    "title": "The Teppa-kulam",
    "photographer": "Linnaeus Tripe",
    "year": "1858",
    "culture": "British",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP119057.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/286803",
    "emotionResonance": [
      "júbilo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buildings"
    ],
    "resonance": {
      "energy": 95,
      "temperature": 78,
      "tension": 22,
      "density": 28,
      "movement": 92,
      "temporality": 48,
      "humanity": 88,
      "clarity": 82,
      "intimacy": 72,
      "control": 72
    },
    "description": "Gilman Collection, Purchase, Cynthia Hazen Polsky Gift, 2005",
    "poeticDescription": "The Teppa-kulam"
  },
  {
    "id": "met-photo-917799",
    "title": "[Merchants' Carnival Portrait: Quaker Meeting House (?)]",
    "photographer": "Unknown",
    "year": "1880s–1890s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP-43423-115.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/917799",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Gift of the Shimshak Brenner Family, in memory of Robert Shimshak, 2024",
    "poeticDescription": "[Merchants' Carnival Portrait: Quaker Meeting House (?)]"
  },
  {
    "id": "met-photo-853599",
    "title": "Photo Views Taken in India, S Martin, Calcutta, 1888",
    "photographer": "Anonymous",
    "year": "dated 1888",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/is/web-large/DP-35321-004.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/853599",
    "emotionResonance": [
      "júbilo"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 95,
      "temperature": 78,
      "tension": 22,
      "density": 28,
      "movement": 92,
      "temporality": 48,
      "humanity": 88,
      "clarity": 82,
      "intimacy": 72,
      "control": 72
    },
    "description": "Gift of James F. Ivory, 2021",
    "poeticDescription": "Photo Views Taken in India, S Martin, Calcutta, 1888"
  },
  {
    "id": "met-photo-283099",
    "title": "Philip Stanhope Worsley",
    "photographer": "Julia Margaret Cameron",
    "year": "1866",
    "culture": "British, born India",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP206679.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/283099",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "portraits",
      "authors"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Gilman Collection, Purchase, The Horace W. Goldsmith Foundation Gift, through Joyce and Robert Menschel, 2005",
    "poeticDescription": "Philip Stanhope Worsley"
  },
  {
    "id": "met-photo-294331",
    "title": "[Montage of Ecclesiastical Figures Posed in Political Satire]",
    "photographer": "Unknown",
    "year": "1860s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP273663.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/294331",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "satire",
      "men"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "The Horace W. Goldsmith Foundation Fund, through Joyce and Robert Menschel, 2012",
    "poeticDescription": "[Montage of Ecclesiastical Figures Posed in Political Satire]"
  },
  {
    "id": "met-photo-294332",
    "title": "[Montage of Ecclesiastical Figures Posed in Political Satire]",
    "photographer": "Unknown",
    "year": "1860s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP273664.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/294332",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "satire",
      "buildings",
      "politics"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "The Horace W. Goldsmith Foundation Fund, through Joyce and Robert Menschel, 2012",
    "poeticDescription": "[Montage of Ecclesiastical Figures Posed in Political Satire]"
  },
  {
    "id": "met-photo-294333",
    "title": "[Montage of Ecclesiastical Figures Posed in Political Satire]",
    "photographer": "Unknown",
    "year": "1860s",
    "culture": "—",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP273670.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/294333",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "satire",
      "men",
      "politics"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "The Horace W. Goldsmith Foundation Fund, through Joyce and Robert Menschel, 2012",
    "poeticDescription": "[Montage of Ecclesiastical Figures Posed in Political Satire]"
  },
  {
    "id": "met-photo-814626",
    "title": "\"The Wilde Woman of Aiken,\" from the \"Aiken and Vicinity\" series",
    "photographer": "James A. Palmer",
    "year": "1882",
    "culture": "American",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ad/web-large/DP-21556-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/814626",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "women",
      "flowers",
      "jugs"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "Purchase, Nancy Dunn Revocable Trust Gift, 2018",
    "poeticDescription": "\"The Wilde Woman of Aiken,\" from the \"Aiken and Vicinity\" series"
  },
  {
    "id": "met-photo-283722",
    "title": "[Boy in Uniform]",
    "photographer": "Jean-Baptiste Frénet",
    "year": "ca. 1855",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP116735.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/283722",
    "emotionResonance": [
      "admiración",
      "orgullo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "boys",
      "portraits"
    ],
    "resonance": {
      "energy": 60,
      "temperature": 62,
      "tension": 30,
      "density": 42,
      "movement": 40,
      "temporality": 50,
      "humanity": 76,
      "clarity": 75,
      "intimacy": 49,
      "control": 62
    },
    "description": "Purchase, Noel and Harriette Levine Gift and Jennifer and Joseph Duke Gift, 2000",
    "poeticDescription": "[Boy in Uniform]"
  },
  {
    "id": "met-photo-268707",
    "title": "Henry Taylor",
    "photographer": "Julia Margaret Cameron",
    "year": "1864",
    "culture": "British, born India",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP295210.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/268707",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "portraits",
      "profiles"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Harris Brisbane Dick Fund, 1941",
    "poeticDescription": "Henry Taylor"
  },
  {
    "id": "met-photo-285644",
    "title": "A Harvest of Death, Gettysburg, Pennsylvania",
    "photographer": "Timothy H. O'Sullivan",
    "year": "July 1863",
    "culture": "American, born Ireland",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP274823.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/285644",
    "emotionResonance": [
      "miedo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "soldiers",
      "american civil war",
      "corpses",
      "death"
    ],
    "resonance": {
      "energy": 72,
      "temperature": 28,
      "tension": 85,
      "density": 62,
      "movement": 58,
      "temporality": 25,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 45,
      "control": 8
    },
    "description": "Gilman Collection, Museum Purchase, 2005",
    "poeticDescription": "A Harvest of Death, Gettysburg, Pennsylvania"
  },
  {
    "id": "met-photo-286941",
    "title": "Jérusalem, Vallée de Josaphat, Faces Ouest et Nord, 1",
    "photographer": "Auguste Salzmann",
    "year": "1854",
    "culture": "French",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP131260.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/286941",
    "emotionResonance": [
      "serenidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "architecture",
      "landscapes"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 52,
      "tension": 10,
      "density": 30,
      "movement": 12,
      "temporality": 75,
      "humanity": 70,
      "clarity": 85,
      "intimacy": 60,
      "control": 82
    },
    "description": "Gilman Collection, Gift of The Howard Gilman Foundation, 2005",
    "poeticDescription": "Jérusalem, Vallée de Josaphat, Faces Ouest et Nord, 1"
  },
  {
    "id": "met-photo-299472",
    "title": "[Plaster Casts of Bodies, Pompeii]",
    "photographer": "Giorgio Sommer",
    "year": "ca. 1875",
    "culture": "Italian, born Germany",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ph/web-large/DP262064.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/299472",
    "emotionResonance": [
      "fobia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "human figures"
    ],
    "resonance": {
      "energy": 82,
      "temperature": 22,
      "tension": 92,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 22
    },
    "description": "Purchase, Harriett Ames Charitable Trust Gift, 2012",
    "poeticDescription": "[Plaster Casts of Bodies, Pompeii]"
  }
];
