import type { Sculpture } from "@/types";

/**
 * Sculptures ingested from the Metropolitan Museum of Art Open Access API.
 * Each piece's ResonanceAxes is derived by averaging the catalogue emotions
 * whose keywords matched its tags. Generated by scripts/ingest-met-sculpture.mjs.
 *
 * Total: 93 sculptures.
 */
export const SCULPTURES_MET: Sculpture[] = [
  {
    "id": "met-sculpt-210774",
    "title": "Pietà",
    "artist": "Jean-Baptiste Carpeaux",
    "year": "1864",
    "medium": "Terracotta",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DT345121.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/210774",
    "emotionResonance": [
      "melancolía"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "christ",
      "virgin mary"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 40,
      "tension": 55,
      "density": 60,
      "movement": 15,
      "temporality": 90,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 75,
      "control": 40
    },
    "description": "Purchase, Assunta Sommella Peluso, Ada Peluso, and Romano I. Peluso Gift, in memory of Ignazio Peluso, 2001",
    "poeticDescription": "Pietà"
  },
  {
    "id": "met-sculpt-473331",
    "title": "Pietà (Vesperbild)",
    "artist": "Anonymous",
    "year": "ca. 1400",
    "medium": "Limestone with polychrome highlight",
    "culture": "Bohemian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/cl/web-large/DT4945.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/473331",
    "emotionResonance": [
      "melancolía"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "christ",
      "virgin mary"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 40,
      "tension": 55,
      "density": 60,
      "movement": 15,
      "temporality": 90,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 75,
      "control": 40
    },
    "description": "The Cloisters Collection, 2001",
    "poeticDescription": "Pietà (Vesperbild)"
  },
  {
    "id": "met-sculpt-197459",
    "title": "Pietà",
    "artist": "Anonymous",
    "year": "second quarter 16th century",
    "medium": "Alabaster, with traces of original polychromy",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/sf33_153_1.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/197459",
    "emotionResonance": [
      "melancolía"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "sadness",
      "christ",
      "virgin mary"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 40,
      "tension": 55,
      "density": 60,
      "movement": 15,
      "temporality": 90,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 75,
      "control": 40
    },
    "description": "Harris Brisbane Dick Fund, 1933",
    "poeticDescription": "Pietà"
  },
  {
    "id": "met-sculpt-627606",
    "title": "Pietà",
    "artist": "Hubert Gerhard",
    "year": "after 1595",
    "medium": "Bronze",
    "culture": "Netherlandish",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-12252-011.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/627606",
    "emotionResonance": [
      "melancolía"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "virgin mary",
      "jesus"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 40,
      "tension": 55,
      "density": 60,
      "movement": 15,
      "temporality": 90,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 75,
      "control": 40
    },
    "description": "Gift of Anthony and Lois Blumka, 2013",
    "poeticDescription": "Pietà"
  },
  {
    "id": "met-sculpt-462776",
    "title": "Pietà (Lamentation)",
    "artist": "Anonymous",
    "year": "early 16th century",
    "medium": "Wood, paint and gilding",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/md/web-large/DP144111.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/462776",
    "emotionResonance": [
      "tristeza",
      "compasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "christ",
      "mary magdalene",
      "virgin mary",
      "saint john"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 34,
      "tension": 47,
      "density": 65,
      "movement": 20,
      "temporality": 80,
      "humanity": 92,
      "clarity": 41,
      "intimacy": 76,
      "control": 40
    },
    "description": "Gift of  two Trustees, 1905",
    "poeticDescription": "Pietà (Lamentation)"
  },
  {
    "id": "met-sculpt-463190",
    "title": "Mourning Virgin",
    "artist": "Anonymous",
    "year": "1510–20",
    "medium": "Limewood",
    "culture": "South German",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/md/web-large/DP214399.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/463190",
    "emotionResonance": [
      "melancolía"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 20,
      "temperature": 40,
      "tension": 55,
      "density": 60,
      "movement": 15,
      "temporality": 90,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 75,
      "control": 40
    },
    "description": "Rogers Fund, 1909",
    "poeticDescription": "Mourning Virgin"
  },
  {
    "id": "met-sculpt-471726",
    "title": "The Lamentation",
    "artist": "Anonymous",
    "year": "ca. 1480",
    "medium": "Walnut with paint and gilding",
    "culture": "Central Spanish",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/cl/web-large/DP366884.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/471726",
    "emotionResonance": [
      "tristeza",
      "admiración",
      "compasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "christ",
      "mary magdalene",
      "saint john the evangelist",
      "virgin mary",
      "lamentation"
    ],
    "resonance": {
      "energy": 32,
      "temperature": 43,
      "tension": 40,
      "density": 57,
      "movement": 26,
      "temporality": 73,
      "humanity": 88,
      "clarity": 51,
      "intimacy": 69,
      "control": 44
    },
    "description": "The Cloisters Collection, 1955",
    "poeticDescription": "The Lamentation"
  },
  {
    "id": "met-sculpt-239242",
    "title": "Lamentation",
    "artist": "Anonymous",
    "year": "early 17th century",
    "medium": "Gilt bronze",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-21733-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/239242",
    "emotionResonance": [
      "tristeza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "women",
      "christ",
      "virgin mary",
      "lamentation"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 35,
      "tension": 45,
      "density": 58,
      "movement": 18,
      "temporality": 72,
      "humanity": 88,
      "clarity": 40,
      "intimacy": 70,
      "control": 42
    },
    "description": "Gift of Joseph G. Reinis, 2012",
    "poeticDescription": "Lamentation"
  },
  {
    "id": "met-sculpt-468707",
    "title": "Mary Magdalene at the Foot of the Cross",
    "artist": "Master of Rimini",
    "year": "ca. 1420–30",
    "medium": "Alabaster",
    "culture": "South Netherlandish",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/md/web-large/sf65-85s7.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/468707",
    "emotionResonance": [
      "soledad"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 18,
      "temperature": 38,
      "tension": 40,
      "density": 48,
      "movement": 12,
      "temporality": 80,
      "humanity": 72,
      "clarity": 55,
      "intimacy": 30,
      "control": 60
    },
    "description": "Gift of Paul W. Doll Jr., 1965",
    "poeticDescription": "Mary Magdalene at the Foot of the Cross"
  },
  {
    "id": "met-sculpt-192714",
    "title": "Bather (from a fountain group)",
    "artist": "Jean Antoine Houdon",
    "year": "1782",
    "medium": "Marble",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP275873.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/192714",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "female nudes",
      "bathing"
    ],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Bequest of Benjamin Altman, 1913",
    "poeticDescription": "Bather (from a fountain group)"
  },
  {
    "id": "met-sculpt-11783",
    "title": "The Arrow Dance",
    "artist": "Louis McClellan Potter",
    "year": "1907",
    "medium": "Bronze",
    "culture": "American",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ad/web-large/1986.343.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/11783",
    "emotionResonance": [
      "pasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "dance",
      "men"
    ],
    "resonance": {
      "energy": 88,
      "temperature": 88,
      "tension": 72,
      "density": 60,
      "movement": 78,
      "temporality": 28,
      "humanity": 85,
      "clarity": 38,
      "intimacy": 88,
      "control": 18
    },
    "description": "Gift of Mr. and Mrs. Edwin C. Stephens, in memory of Helen Tresch, 1986",
    "poeticDescription": "The Arrow Dance"
  },
  {
    "id": "met-sculpt-201862",
    "title": "Paris",
    "artist": "Antico (Pier Jacopo Alari Bonacolsi)",
    "year": "ca. 1518–1524",
    "medium": "Bronze, partially fire-gilt, silver inlay",
    "culture": "Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP229778.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/201862",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "apples",
      "male nudes"
    ],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Edith Perry Chapman Fund, 1955",
    "poeticDescription": "Paris"
  },
  {
    "id": "met-sculpt-37611",
    "title": "Manjuvajra and Vidyadhara in Ecstatic Embrace (Yab-Yum)",
    "artist": "Anonymous",
    "year": "ca. 17th–18th century",
    "medium": "Gilt bronze inlaid with turquoise and carnelian",
    "culture": "Tibet",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/1987_201_O1.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/37611",
    "emotionResonance": [
      "amor",
      "compasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddhism",
      "bodhisattvas"
    ],
    "resonance": {
      "energy": 39,
      "temperature": 54,
      "tension": 43,
      "density": 64,
      "movement": 34,
      "temporality": 74,
      "humanity": 97,
      "clarity": 46,
      "intimacy": 89,
      "control": 39
    },
    "description": "Gift of R. Max Loehr, 1987",
    "poeticDescription": "Manjuvajra and Vidyadhara in Ecstatic Embrace (Yab-Yum)"
  },
  {
    "id": "met-sculpt-543899",
    "title": "The King's Acquaintances Memi and Sabu",
    "artist": "Anonymous",
    "year": "ca. 2575–2465 B.C.",
    "medium": "Limestone, paint",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DT8836.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/543899",
    "emotionResonance": [
      "amor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "couples",
      "men",
      "women"
    ],
    "resonance": {
      "energy": 55,
      "temperature": 75,
      "tension": 38,
      "density": 55,
      "movement": 45,
      "temporality": 60,
      "humanity": 98,
      "clarity": 50,
      "intimacy": 95,
      "control": 40
    },
    "description": "Rogers Fund, 1948",
    "poeticDescription": "The King's Acquaintances Memi and Sabu"
  },
  {
    "id": "met-sculpt-39249",
    "title": "Shiva Embracing His Consort, Uma (Alinganamurti)",
    "artist": "Anonymous",
    "year": "late 11th century",
    "medium": "Copper alloy",
    "culture": "India (Tamil Nadu)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP-14791-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/39249",
    "emotionResonance": [
      "amor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "parvati",
      "shiva"
    ],
    "resonance": {
      "energy": 55,
      "temperature": 75,
      "tension": 38,
      "density": 55,
      "movement": 45,
      "temporality": 60,
      "humanity": 98,
      "clarity": 50,
      "intimacy": 95,
      "control": 40
    },
    "description": "Samuel Eilenberg Collection, Bequest of Samuel Eilenberg, 1998",
    "poeticDescription": "Shiva Embracing His Consort, Uma (Alinganamurti)"
  },
  {
    "id": "met-sculpt-239584",
    "title": "Marble sarcophagus with garlands",
    "artist": "Anonymous",
    "year": "ca. 200–225 CE",
    "medium": "Marble, Proconnesian",
    "culture": "Roman",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP140135.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/239584",
    "emotionResonance": [
      "horror"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "animals",
      "garlands",
      "hunting",
      "medusa"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 18,
      "tension": 98,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 2
    },
    "description": "Gift of Abdo Debbas, 1870",
    "poeticDescription": "Marble sarcophagus with garlands"
  },
  {
    "id": "met-sculpt-320599",
    "title": "Seated mother and child from an ikoro drum(?)",
    "artist": "Mbembe artist",
    "year": "15th–17th century",
    "medium": "Wood, pigment, resin, nails",
    "culture": "Mbembe peoples",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ao/web-large/dp229195.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/320599",
    "emotionResonance": [
      "ternura",
      "serenidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "women"
    ],
    "resonance": {
      "energy": 24,
      "temperature": 62,
      "tension": 10,
      "density": 34,
      "movement": 19,
      "temporality": 70,
      "humanity": 83,
      "clarity": 77,
      "intimacy": 76,
      "control": 74
    },
    "description": "Purchase, 2010 and 2008 Benefit Funds, Laura G. and James J. Ross, David and Holly Ross, Noah-Sadie K. Wachtel Foundation Inc. and Mrs. Howard J. Barnet Gifts, 2010",
    "poeticDescription": "Seated mother and child from an ikoro drum(?)"
  },
  {
    "id": "met-sculpt-843968",
    "title": "Mother and Child",
    "artist": "Bartolomeo Pinelli",
    "year": "1812",
    "medium": "Terracotta",
    "culture": "Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-21676-036.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/843968",
    "emotionResonance": [
      "ternura"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "infants",
      "mothers",
      "women"
    ],
    "resonance": {
      "energy": 28,
      "temperature": 72,
      "tension": 10,
      "density": 38,
      "movement": 25,
      "temporality": 65,
      "humanity": 96,
      "clarity": 68,
      "intimacy": 92,
      "control": 65
    },
    "description": "Bequest of James David Draper, 2019",
    "poeticDescription": "Mother and Child"
  },
  {
    "id": "met-sculpt-470311",
    "title": "Enthroned Virgin and Child",
    "artist": "Anonymous",
    "year": "ca. 1130–1140",
    "medium": "Birch with paint and glass",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/cl/web-large/DP167494.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/470311",
    "emotionResonance": [
      "soberbia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "madonna and child",
      "virgin mary",
      "jesus"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 62,
      "tension": 32,
      "density": 42,
      "movement": 42,
      "temporality": 42,
      "humanity": 22,
      "clarity": 78,
      "intimacy": 22,
      "control": 72
    },
    "description": "The Cloisters Collection, 1947",
    "poeticDescription": "Enthroned Virgin and Child"
  },
  {
    "id": "met-sculpt-314376",
    "title": "Mother and Child Figure",
    "artist": "Dogon blacksmith",
    "year": "15th–19th century",
    "medium": "Wood",
    "culture": "Dogon peoples",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ao/web-large/1981.398.1_a.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/314376",
    "emotionResonance": [
      "ternura"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "infants",
      "mothers"
    ],
    "resonance": {
      "energy": 28,
      "temperature": 72,
      "tension": 10,
      "density": 38,
      "movement": 25,
      "temporality": 65,
      "humanity": 96,
      "clarity": 68,
      "intimacy": 92,
      "control": 65
    },
    "description": "Gift of John and Evelyn Kossak, The Kronos Collections, 1981",
    "poeticDescription": "Mother and Child Figure"
  },
  {
    "id": "met-sculpt-312642",
    "title": "Warrior",
    "artist": "Chiriquí artist(s)",
    "year": "300–800 CE",
    "medium": "Volcanic stone",
    "culture": "Chiriquí, Aguas Buenas Phase",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ao/web-large/DP-23863-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/312642",
    "emotionResonance": [
      "ira"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "heads",
      "warriors"
    ],
    "resonance": {
      "energy": 90,
      "temperature": 92,
      "tension": 92,
      "density": 65,
      "movement": 88,
      "temporality": 22,
      "humanity": 78,
      "clarity": 55,
      "intimacy": 28,
      "control": 12
    },
    "description": "The Michael C. Rockefeller Memorial Collection, Bequest of Nelson A. Rockefeller, 1979",
    "poeticDescription": "Warrior"
  },
  {
    "id": "met-sculpt-197033",
    "title": "A Young Warrior",
    "artist": "Tullio Lombardo",
    "year": "1490s",
    "medium": "White marble",
    "culture": "Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP200059.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/197033",
    "emotionResonance": [
      "ira"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "armor",
      "men",
      "warriors"
    ],
    "resonance": {
      "energy": 90,
      "temperature": 92,
      "tension": 92,
      "density": 65,
      "movement": 88,
      "temporality": 22,
      "humanity": 78,
      "clarity": 55,
      "intimacy": 28,
      "control": 12
    },
    "description": "The Friedsam Collection, Bequest of Michael Friedsam, 1931",
    "poeticDescription": "A Young Warrior"
  },
  {
    "id": "met-sculpt-251929",
    "title": "Marble statue of a wounded warrior",
    "artist": "Anonymous",
    "year": "ca. 138–181 CE",
    "medium": "Marble",
    "culture": "Roman",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP-39853-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/251929",
    "emotionResonance": [
      "ira",
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "male nudes"
    ],
    "resonance": {
      "energy": 63,
      "temperature": 70,
      "tension": 82,
      "density": 62,
      "movement": 53,
      "temporality": 40,
      "humanity": 80,
      "clarity": 44,
      "intimacy": 40,
      "control": 22
    },
    "description": "Frederick C. Hewitt Fund, 1925",
    "poeticDescription": "Marble statue of a wounded warrior"
  },
  {
    "id": "met-sculpt-194910",
    "title": "Warrior",
    "artist": "Anonymous",
    "year": "16th century",
    "medium": "Bronze",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-15401-112.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/194910",
    "emotionResonance": [
      "ira",
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "male nudes"
    ],
    "resonance": {
      "energy": 63,
      "temperature": 70,
      "tension": 82,
      "density": 62,
      "movement": 53,
      "temporality": 40,
      "humanity": 80,
      "clarity": 44,
      "intimacy": 40,
      "control": 22
    },
    "description": "Bequest of Michael Dreicer, 1921",
    "poeticDescription": "Warrior"
  },
  {
    "id": "met-sculpt-307635",
    "title": "Coiled serpent",
    "artist": "Mexica artist(s)",
    "year": "1325–1521 CE",
    "medium": "Stone",
    "culture": "Mexica (Aztec)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ao/web-large/DP-23819-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/307635",
    "emotionResonance": [
      "miedo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "serpents"
    ],
    "resonance": {
      "energy": 72,
      "temperature": 28,
      "tension": 85,
      "density": 62,
      "movement": 58,
      "temporality": 25,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 45,
      "control": 8
    },
    "description": "Museum Purchase, 1900",
    "poeticDescription": "Coiled serpent"
  },
  {
    "id": "met-sculpt-320347",
    "title": "Feathered serpent head",
    "artist": "Teotihuacan artist(s)",
    "year": "100-500 CE",
    "medium": "Stone, pigment",
    "culture": "Teotihuacan",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ao/web-large/DP-39201-004.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/320347",
    "emotionResonance": [
      "miedo"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 72,
      "temperature": 28,
      "tension": 85,
      "density": 62,
      "movement": 58,
      "temporality": 25,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 45,
      "control": 8
    },
    "description": "Museum Purchase, 1900",
    "poeticDescription": "Feathered serpent head"
  },
  {
    "id": "met-sculpt-205413",
    "title": "Nymph drying her hair",
    "artist": "Louis Claude Vassé",
    "year": "1761–63",
    "medium": "Nymph: white marble: base, basin and console: gray-veined marble; serpents: bronze, with remains of gilding",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/210512.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/205413",
    "emotionResonance": [
      "miedo",
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "female nudes",
      "nymphs"
    ],
    "resonance": {
      "energy": 54,
      "temperature": 38,
      "tension": 79,
      "density": 60,
      "movement": 38,
      "temporality": 42,
      "humanity": 84,
      "clarity": 34,
      "intimacy": 49,
      "control": 20
    },
    "description": "Purchase, Josephine Bay Paul and C. Michael Paul Foundation Inc. Gift, Charles Ulrick and Josephine Bay Foundation Inc. Gift, and Rogers Fund, 1971",
    "poeticDescription": "Nymph drying her hair"
  },
  {
    "id": "met-sculpt-39544",
    "title": "Vishnu Resting on the Serpent Shesha (Vishnu Anantashayin)",
    "artist": "Anonymous",
    "year": "ca. 921–45",
    "medium": "Stone",
    "culture": "Cambodia",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/1996_466.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/39544",
    "emotionResonance": [
      "miedo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "serpents",
      "vishnu",
      "hinduism"
    ],
    "resonance": {
      "energy": 72,
      "temperature": 28,
      "tension": 85,
      "density": 62,
      "movement": 58,
      "temporality": 25,
      "humanity": 85,
      "clarity": 35,
      "intimacy": 45,
      "control": 8
    },
    "description": "Samuel Eilenberg Collection, Gift of Samuel Eilenberg, 1996",
    "poeticDescription": "Vishnu Resting on the Serpent Shesha (Vishnu Anantashayin)"
  },
  {
    "id": "met-sculpt-470601",
    "title": "Angel",
    "artist": "Anonymous",
    "year": "ca. 1130",
    "medium": "Limestone",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/cl/web-large/DP102898.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/470601",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "angels"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "The Cloisters Collection, 1947",
    "poeticDescription": "Angel"
  },
  {
    "id": "met-sculpt-206288",
    "title": "Angel",
    "artist": "Christian Jorhan the Elder",
    "year": "mid-18th century",
    "medium": "Lindenwood, gilded and with original polychromy",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/CT_17351.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/206288",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "angels"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "The Lesley and Emma Sheafer Collection, Bequest of Emma A. Sheafer, 1973",
    "poeticDescription": "Angel"
  },
  {
    "id": "met-sculpt-206289",
    "title": "Angel",
    "artist": "Christian Jorhan the Elder",
    "year": "mid-18th century",
    "medium": "Lindenwood, gilded and with original polychromy",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/CT_17352.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/206289",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "angels"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "The Lesley and Emma Sheafer Collection, Bequest of Emma A. Sheafer, 1973",
    "poeticDescription": "Angel"
  },
  {
    "id": "met-sculpt-467737",
    "title": "Angel",
    "artist": "Anonymous",
    "year": "ca. 1360–70",
    "medium": "Elephant ivory",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/md/web-large/sf41-100-164s1.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/467737",
    "emotionResonance": [
      "admiración"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 52,
      "temperature": 62,
      "tension": 28,
      "density": 42,
      "movement": 38,
      "temporality": 58,
      "humanity": 80,
      "clarity": 72,
      "intimacy": 55,
      "control": 52
    },
    "description": "Gift of George Blumenthal, 1941",
    "poeticDescription": "Angel"
  },
  {
    "id": "met-sculpt-547777",
    "title": "Male god",
    "artist": "Anonymous",
    "year": "ca. 1390–1352 B.C.",
    "medium": "Granodiorite",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP-24214-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/547777",
    "emotionResonance": [
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 55,
      "density": 45,
      "movement": 42,
      "temporality": 88,
      "humanity": 55,
      "clarity": 42,
      "intimacy": 28,
      "control": 35
    },
    "description": "Rogers Fund, 1919 (19.2.15); Fletcher Fund, 1996 (1996.362)",
    "poeticDescription": "Male god"
  },
  {
    "id": "met-sculpt-587598",
    "title": "Statue of the God Ptah",
    "artist": "Anonymous",
    "year": "ca. 1070–712 BCE",
    "medium": "Bronze, gold leaf, glass",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP216330.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/587598",
    "emotionResonance": [
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 55,
      "density": 45,
      "movement": 42,
      "temporality": 88,
      "humanity": 55,
      "clarity": 42,
      "intimacy": 28,
      "control": 35
    },
    "description": "Purchase, Gift in memory of Manuel Schnitzer, 2009",
    "poeticDescription": "Statue of the God Ptah"
  },
  {
    "id": "met-sculpt-544874",
    "title": "Statuette of Amun",
    "artist": "Anonymous",
    "year": "ca. 945–712 BCE",
    "medium": "Gold",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP-38626-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/544874",
    "emotionResonance": [
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "amun"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 55,
      "density": 45,
      "movement": 42,
      "temporality": 88,
      "humanity": 55,
      "clarity": 42,
      "intimacy": 28,
      "control": 35
    },
    "description": "Purchase, Edward S. Harkness Gift, 1926",
    "poeticDescription": "Statuette of Amun"
  },
  {
    "id": "met-sculpt-543882",
    "title": "King Sahure Accompanied by a Divine Figure",
    "artist": "Anonymous",
    "year": "ca. 2458–2446 B.C.",
    "medium": "Gneiss",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP-1691-03.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/543882",
    "emotionResonance": [
      "sublimidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "kings",
      "men"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 55,
      "density": 45,
      "movement": 42,
      "temporality": 88,
      "humanity": 55,
      "clarity": 42,
      "intimacy": 28,
      "control": 35
    },
    "description": "Rogers Fund, 1918",
    "poeticDescription": "King Sahure Accompanied by a Divine Figure"
  },
  {
    "id": "met-sculpt-38160",
    "title": "Buddha",
    "artist": "Anonymous",
    "year": "mid-7th century",
    "medium": "Sandstone",
    "culture": "Cambodia or Vietnam",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/LK.1993.477.3_DP310135r1_25F.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38160",
    "emotionResonance": [
      "trascendencia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddha"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 72,
      "clarity": 78,
      "intimacy": 68,
      "control": 58
    },
    "description": "Gift of Florence and Herbert Irving, 1993",
    "poeticDescription": "Buddha"
  },
  {
    "id": "met-sculpt-646117",
    "title": "Buddha",
    "artist": "Anonymous",
    "year": "3rd century",
    "medium": "Schist",
    "culture": "Pakistan, Khyber-Pakhtunkhwa province, possibly Takht-i-bahi monastery, ancient region of Gandhara",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP328363.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/646117",
    "emotionResonance": [
      "trascendencia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "gandhara",
      "buddhism",
      "buddha"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 72,
      "clarity": 78,
      "intimacy": 68,
      "control": 58
    },
    "description": "Purchase, Denise and Andrew Saul Gift, in honor of Maxwell K. Hearn, 2014",
    "poeticDescription": "Buddha"
  },
  {
    "id": "met-sculpt-75414",
    "title": "Buddha",
    "artist": "Anonymous",
    "year": "18th century",
    "medium": "Copper alloy with gilding",
    "culture": "Sri Lanka, Kandy district",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP219474.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/75414",
    "emotionResonance": [
      "trascendencia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddhism",
      "buddha"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 72,
      "clarity": 78,
      "intimacy": 68,
      "control": 58
    },
    "description": "Purchase, Louis V. Bell, Harris Brisbane Dick, Fletcher, and Rogers Funds and Joseph Pulitzer Bequest; The Miriam and Ira D. Wallach Foundation Fund; Florence and Herbert Irving, Cynthia Hazen Polsky and Anne H. Bass Gifts, 2010",
    "poeticDescription": "Buddha"
  },
  {
    "id": "met-sculpt-38237",
    "title": "Buddha",
    "artist": "Anonymous",
    "year": "3rd century CE",
    "medium": "Limestone",
    "culture": "India,  Andhra Pradesh",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP701399.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38237",
    "emotionResonance": [
      "trascendencia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "early andhra",
      "buddhism",
      "buddha"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 52,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 72,
      "clarity": 78,
      "intimacy": 68,
      "control": 58
    },
    "description": "Purchase, The Vincent Astor Foundation Gift, Brooke Russell Astor Bequest, The Miriam and Ira D. Wallach Foundation Fund; Fernando Family Trust Gift, in honor of Dr. Quintus and Mrs. Wimala Fernando; Vijay K. Anand, M.D., Nanda Anand, Maya Anand, and Rohit Anand, and The Estate of Mamdouha Bobst Gifts, 2016",
    "poeticDescription": "Buddha"
  },
  {
    "id": "met-sculpt-61660",
    "title": "Bodhisattva",
    "artist": "Anonymous",
    "year": "12th–13th century",
    "medium": "Marble with pigment",
    "culture": "China",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP170131.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/61660",
    "emotionResonance": [
      "compasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "bodhisattvas"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 95,
      "clarity": 42,
      "intimacy": 82,
      "control": 38
    },
    "description": "Fletcher Fund, 1934",
    "poeticDescription": "Bodhisattva"
  },
  {
    "id": "met-sculpt-36085",
    "title": "Bodhisattva",
    "artist": "Anonymous",
    "year": "11th–12th century",
    "medium": "Wood (foxglove) with traces of pigment and gilding; single woodblock construction",
    "culture": "China",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP164027.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/36085",
    "emotionResonance": [
      "compasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddhism",
      "bodhisattvas"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 95,
      "clarity": 42,
      "intimacy": 82,
      "control": 38
    },
    "description": "Gift of D. Herbert Beskind, 1961",
    "poeticDescription": "Bodhisattva"
  },
  {
    "id": "met-sculpt-38950",
    "title": "Bodhisattva Avalokiteshvara",
    "artist": "Anonymous",
    "year": "second quarter of the 8th century",
    "medium": "Copper alloy inlaid with silver and glass or obsidian",
    "culture": "Plai Bat II Temple, Lahan Sai District, Buriram Province, Thailand",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/LK_DP316445r3_25AA.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38950",
    "emotionResonance": [
      "compasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddhism",
      "avalokiteshvara",
      "bodhisattvas"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 95,
      "clarity": 42,
      "intimacy": 82,
      "control": 38
    },
    "description": "Rogers Fund, 1967",
    "poeticDescription": "Bodhisattva Avalokiteshvara"
  },
  {
    "id": "met-sculpt-57612",
    "title": "Bodhisattva Manjushri",
    "artist": "Anonymous",
    "year": "",
    "medium": "Gilt copper alloy",
    "culture": "China",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP164061.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/57612",
    "emotionResonance": [
      "compasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "swords",
      "buddhism",
      "bodhisattvas",
      "manjushri"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 95,
      "clarity": 42,
      "intimacy": 82,
      "control": 38
    },
    "description": "Rogers Fund, 2001",
    "poeticDescription": "Bodhisattva Manjushri"
  },
  {
    "id": "met-sculpt-72301",
    "title": "Buddha Seated in Meditation",
    "artist": "Anonymous",
    "year": "16th century",
    "medium": "Copper alloy with gilding",
    "culture": "Sri Lanka. western regions",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP219472.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/72301",
    "emotionResonance": [
      "trascendencia",
      "serenidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddhism",
      "buddha"
    ],
    "resonance": {
      "energy": 44,
      "temperature": 52,
      "tension": 19,
      "density": 36,
      "movement": 42,
      "temporality": 52,
      "humanity": 71,
      "clarity": 82,
      "intimacy": 64,
      "control": 70
    },
    "description": "Purchase, Louis V. Bell, Harris Brisbane Dick, Fletcher, and Rogers Funds and Joseph Pulitzer Bequest; The Miriam and Ira D. Wallach Foundation Fund; Florence and Herbert Irving, Cynthia Hazen Polsky and Anne H. Bass Gifts, 2010",
    "poeticDescription": "Buddha Seated in Meditation"
  },
  {
    "id": "met-sculpt-38574",
    "title": "Jain Svetambara Tirthankara in Meditation",
    "artist": "Anonymous",
    "year": "first half of the 11th century",
    "medium": "Marble",
    "culture": "India (Gujarat or Rajasthan)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DT5161.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38574",
    "emotionResonance": [
      "serenidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 52,
      "tension": 10,
      "density": 30,
      "movement": 12,
      "temporality": 75,
      "humanity": 70,
      "clarity": 85,
      "intimacy": 60,
      "control": 82
    },
    "description": "Purchase, Florence and Herbert Irving Gift, 1992",
    "poeticDescription": "Jain Svetambara Tirthankara in Meditation"
  },
  {
    "id": "met-sculpt-39193",
    "title": "Jain Digambara Tirthanhara Standing in Kayotsarga Meditation Posture",
    "artist": "Anonymous",
    "year": "12th century",
    "medium": "Copper alloy",
    "culture": "India (Deccan, Karnataka)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP-593-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/39193",
    "emotionResonance": [
      "serenidad",
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "male nudes"
    ],
    "resonance": {
      "energy": 28,
      "temperature": 50,
      "tension": 41,
      "density": 44,
      "movement": 15,
      "temporality": 67,
      "humanity": 76,
      "clarity": 59,
      "intimacy": 56,
      "control": 57
    },
    "description": "Gift of Florence and Herbert Irving, 2015",
    "poeticDescription": "Jain Digambara Tirthanhara Standing in Kayotsarga Meditation Posture"
  },
  {
    "id": "met-sculpt-61821",
    "title": "Bodhidharma Seated in Meditation",
    "artist": "Anonymous",
    "year": "",
    "medium": "Cast iron",
    "culture": "China",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/1975_413_F.JPG",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/61821",
    "emotionResonance": [
      "serenidad"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "buddhism"
    ],
    "resonance": {
      "energy": 20,
      "temperature": 52,
      "tension": 10,
      "density": 30,
      "movement": 12,
      "temporality": 75,
      "humanity": 70,
      "clarity": 85,
      "intimacy": 60,
      "control": 82
    },
    "description": "Gift of Fong Chow, in memory of his grandparents, Sir Shouson and Lady Yip Chow, 1975",
    "poeticDescription": "Bodhidharma Seated in Meditation"
  },
  {
    "id": "met-sculpt-207613",
    "title": "Triumph",
    "artist": "Coriolanus Master",
    "year": "early 16th century",
    "medium": "Bronze",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/240931.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/207613",
    "emotionResonance": [
      "júbilo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "horses",
      "chariots"
    ],
    "resonance": {
      "energy": 95,
      "temperature": 78,
      "tension": 22,
      "density": 28,
      "movement": 92,
      "temporality": 48,
      "humanity": 88,
      "clarity": 82,
      "intimacy": 72,
      "control": 72
    },
    "description": "The Erich Lederer Collection, Gift of Mrs. Erich Lederer, 1986",
    "poeticDescription": "Triumph"
  },
  {
    "id": "met-sculpt-254819",
    "title": "Marble sarcophagus with the Triumph of Dionysos and the Seasons",
    "artist": "Anonymous",
    "year": "ca. 260–270 CE",
    "medium": "Marble",
    "culture": "Roman",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP-14287-144.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/254819",
    "emotionResonance": [
      "júbilo",
      "vergüenza",
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "animals",
      "men",
      "male nudes",
      "dionysus",
      "satyrs"
    ],
    "resonance": {
      "energy": 66,
      "temperature": 66,
      "tension": 41,
      "density": 43,
      "movement": 61,
      "temporality": 45,
      "humanity": 79,
      "clarity": 65,
      "intimacy": 59,
      "control": 54
    },
    "description": "Purchase, Joseph Pulitzer Bequest, 1955",
    "poeticDescription": "Marble sarcophagus with the Triumph of Dionysos and the Seasons"
  },
  {
    "id": "met-sculpt-203921",
    "title": "Triumph of Neptune",
    "artist": "Alvise of Padua",
    "year": "ca. 1515–25",
    "medium": "Bronze",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-1357-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/203921",
    "emotionResonance": [
      "júbilo",
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "male nudes",
      "female nudes",
      "neptune",
      "horses"
    ],
    "resonance": {
      "energy": 65,
      "temperature": 63,
      "tension": 47,
      "density": 43,
      "movement": 55,
      "temporality": 53,
      "humanity": 85,
      "clarity": 57,
      "intimacy": 62,
      "control": 52
    },
    "description": "Gift of Irwin Untermyer, 1964",
    "poeticDescription": "Triumph of Neptune"
  },
  {
    "id": "met-sculpt-460535",
    "title": "Cameo with the Triumph of Bacchus",
    "artist": "Anonymous",
    "year": "second quarter 19th century",
    "medium": "Onyx",
    "culture": "probably Austrian or Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/rl/web-large/SF-1975-1-1532.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/460535",
    "emotionResonance": [
      "júbilo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "centaurs",
      "bacchus"
    ],
    "resonance": {
      "energy": 95,
      "temperature": 78,
      "tension": 22,
      "density": 28,
      "movement": 92,
      "temporality": 48,
      "humanity": 88,
      "clarity": 82,
      "intimacy": 72,
      "control": 72
    },
    "description": "Robert Lehman Collection, 1975",
    "poeticDescription": "Cameo with the Triumph of Bacchus"
  },
  {
    "id": "met-sculpt-249256",
    "title": "Cameo glass disk with Medusa head",
    "artist": "Anonymous",
    "year": "1st century CE",
    "medium": "Glass",
    "culture": "Roman",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP155147.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/249256",
    "emotionResonance": [
      "horror"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "medusa"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 18,
      "tension": 98,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 2
    },
    "description": "Gift of J. Pierpont Morgan, 1917",
    "poeticDescription": "Cameo glass disk with Medusa head"
  },
  {
    "id": "met-sculpt-242149",
    "title": "Limestone votive head",
    "artist": "Anonymous",
    "year": "3rd–1st century BCE",
    "medium": "Limestone",
    "culture": "Cypriot",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP214185.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/242149",
    "emotionResonance": [
      "horror"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "heads"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 18,
      "tension": 98,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 2
    },
    "description": "The Cesnola Collection, Purchased by subscription, 1874–76",
    "poeticDescription": "Limestone votive head"
  },
  {
    "id": "met-sculpt-244991",
    "title": "Peridot ring stone",
    "artist": "Anonymous",
    "year": "ca. 1st century BCE–3rd century CE",
    "medium": "Peridot",
    "culture": "Roman",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP141762.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/244991",
    "emotionResonance": [
      "horror"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "heads",
      "medusa"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 18,
      "tension": 98,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 2
    },
    "description": "Gift of John Taylor Johnston, 1881",
    "poeticDescription": "Peridot ring stone"
  },
  {
    "id": "met-sculpt-204759",
    "title": "Head of Medusa",
    "artist": "Antonio Canova",
    "year": "1806–7",
    "medium": "Plaster cast, with modern metal rod",
    "culture": "Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-14050-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/204759",
    "emotionResonance": [
      "horror"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "heads",
      "medusa"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 18,
      "tension": 98,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 2
    },
    "description": "Fletcher Fund, 1967",
    "poeticDescription": "Head of Medusa"
  },
  {
    "id": "met-sculpt-566713",
    "title": "Statuette of a nude woman with moveable arms, one missing",
    "artist": "Anonymous",
    "year": "ca. 945–664 BC",
    "medium": "Boxwood",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/58.36_EGDP012255.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/566713",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Funds from various donors, 1958",
    "poeticDescription": "Statuette of a nude woman with moveable arms, one missing"
  },
  {
    "id": "met-sculpt-544224",
    "title": "Female figure",
    "artist": "Anonymous",
    "year": "ca. 1981–1550 B.C.",
    "medium": "Limestone",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/30.8.198_EGDP019685.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/544224",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "female nudes"
    ],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Theodore M. Davis Collection, Bequest of Theodore M. Davis, 1915",
    "poeticDescription": "Female figure"
  },
  {
    "id": "met-sculpt-552504",
    "title": "Female figure holding infant",
    "artist": "Anonymous",
    "year": "664–332 B.C.",
    "medium": "Terracotta",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP-26355-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/552504",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Rogers Fund, 1926",
    "poeticDescription": "Female figure holding infant"
  },
  {
    "id": "met-sculpt-552505",
    "title": "Female figure",
    "artist": "Anonymous",
    "year": "ca. 664–332 B.C.",
    "medium": "Terracotta",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP-26356-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/552505",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Rogers Fund, 1926",
    "poeticDescription": "Female figure"
  },
  {
    "id": "met-sculpt-39328",
    "title": "Shiva as Lord of Dance (Nataraja)",
    "artist": "Anonymous",
    "year": "ca. late 11th century",
    "medium": "Copper alloy",
    "culture": "Indian (Tamil Nadu)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DT240.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/39328",
    "emotionResonance": [
      "pasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "dancing",
      "shiva"
    ],
    "resonance": {
      "energy": 88,
      "temperature": 88,
      "tension": 72,
      "density": 60,
      "movement": 78,
      "temporality": 28,
      "humanity": 85,
      "clarity": 38,
      "intimacy": 88,
      "control": 18
    },
    "description": "Gift of R. H. Ellsworth Ltd., in honor of Susan Dillon, 1987",
    "poeticDescription": "Shiva as Lord of Dance (Nataraja)"
  },
  {
    "id": "met-sculpt-253483",
    "title": "Marble relief with a dancing maenad",
    "artist": "Kallimachos",
    "year": "ca. 27 BCE–14 CE",
    "medium": "Marble, Pentelic",
    "culture": "Roman",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP116946.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/253483",
    "emotionResonance": [
      "pasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "women",
      "dancing",
      "maenads"
    ],
    "resonance": {
      "energy": 88,
      "temperature": 88,
      "tension": 72,
      "density": 60,
      "movement": 78,
      "temporality": 28,
      "humanity": 85,
      "clarity": 38,
      "intimacy": 88,
      "control": 18
    },
    "description": "Fletcher Fund, 1935",
    "poeticDescription": "Marble relief with a dancing maenad"
  },
  {
    "id": "met-sculpt-546440",
    "title": "Figurine of a Pygmy Dance Leader",
    "artist": "Anonymous",
    "year": "ca. 1950–1885 B.C.",
    "medium": "Ivory",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DT228011.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/546440",
    "emotionResonance": [
      "vergüenza",
      "pasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "male nudes",
      "dancers"
    ],
    "resonance": {
      "energy": 62,
      "temperature": 68,
      "tension": 72,
      "density": 59,
      "movement": 48,
      "temporality": 43,
      "humanity": 84,
      "clarity": 35,
      "intimacy": 70,
      "control": 25
    },
    "description": "Rogers Fund, 1934",
    "poeticDescription": "Figurine of a Pygmy Dance Leader"
  },
  {
    "id": "met-sculpt-551343",
    "title": "Statuette of a dancing dwarf",
    "artist": "Anonymous",
    "year": "332–150 B.C.",
    "medium": "Marble",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP239657.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/551343",
    "emotionResonance": [
      "pasión"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men",
      "dancing"
    ],
    "resonance": {
      "energy": 88,
      "temperature": 88,
      "tension": 72,
      "density": 60,
      "movement": 78,
      "temporality": 28,
      "humanity": 85,
      "clarity": 38,
      "intimacy": 88,
      "control": 18
    },
    "description": "Purchase, Edward S. Harkness Gift, 1926",
    "poeticDescription": "Statuette of a dancing dwarf"
  },
  {
    "id": "met-sculpt-257559",
    "title": "Terracotta Statuette of a Male Dwarf",
    "artist": "Anonymous",
    "year": "2nd century BCE",
    "medium": "Terracotta",
    "culture": "Greek",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP263132.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/257559",
    "emotionResonance": [
      "anhelo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 60,
      "tension": 55,
      "density": 45,
      "movement": 35,
      "temporality": 75,
      "humanity": 85,
      "clarity": 38,
      "intimacy": 72,
      "control": 30
    },
    "description": "Gift of Peter Sharrer, 2000",
    "poeticDescription": "Terracotta Statuette of a Male Dwarf"
  },
  {
    "id": "met-sculpt-38122",
    "title": "Seated Buddha Reaching Enlightenment, Flanked by Avalokiteshvara and Maitreya",
    "artist": "Anonymous",
    "year": "late 10th–11th century",
    "medium": "Black schist",
    "culture": "India, Bihar, Nalanda monastery",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/6 DP310502r3_61A.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38122",
    "emotionResonance": [
      "trascendencia",
      "serenidad",
      "anhelo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddhism",
      "avalokiteshvara",
      "buddha",
      "maitreya"
    ],
    "resonance": {
      "energy": 43,
      "temperature": 55,
      "tension": 31,
      "density": 39,
      "movement": 40,
      "temporality": 59,
      "humanity": 76,
      "clarity": 67,
      "intimacy": 67,
      "control": 57
    },
    "description": "Rogers Fund, 1920",
    "poeticDescription": "Seated Buddha Reaching Enlightenment, Flanked by Avalokiteshvara and Maitreya"
  },
  {
    "id": "met-sculpt-254991",
    "title": "Bronze horse",
    "artist": "Anonymous",
    "year": "ca. 570–560 BCE",
    "medium": "Bronze",
    "culture": "South Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/179407.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/254991",
    "emotionResonance": [
      "anhelo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "horses"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 60,
      "tension": 55,
      "density": 45,
      "movement": 35,
      "temporality": 75,
      "humanity": 85,
      "clarity": 38,
      "intimacy": 72,
      "control": 30
    },
    "description": "Lent in 1907 by Junius Spencer Morgan (1867–1932) and given by his heirs in 1958-1959",
    "poeticDescription": "Bronze horse"
  },
  {
    "id": "met-sculpt-207554",
    "title": "Despairing Adolescent",
    "artist": "Auguste Rodin",
    "year": "modeled 1882, cast 1980",
    "medium": "Bronze",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-13617-042.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/207554",
    "emotionResonance": [
      "anhelo"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 60,
      "tension": 55,
      "density": 45,
      "movement": 35,
      "temporality": 75,
      "humanity": 85,
      "clarity": 38,
      "intimacy": 72,
      "control": 30
    },
    "description": "Gift of Iris and B. Gerald Cantor Foundation, 1986",
    "poeticDescription": "Despairing Adolescent"
  },
  {
    "id": "met-sculpt-249223",
    "title": "Carved amber bow of a fibula (safety pin)",
    "artist": "Anonymous",
    "year": "ca. 500 BCE",
    "medium": "Amber",
    "culture": "Etruscan",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP109258.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/249223",
    "emotionResonance": [
      "resignación"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "couples",
      "men",
      "women"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 85,
      "clarity": 42,
      "intimacy": 72,
      "control": 38
    },
    "description": "Gift of J. Pierpont Morgan, 1917",
    "poeticDescription": "Carved amber bow of a fibula (safety pin)"
  },
  {
    "id": "met-sculpt-544964",
    "title": "Relief with offerings and bowing officials",
    "artist": "Anonymous",
    "year": "ca. 1353–1336 B.C.",
    "medium": "Limestone, paint (mostly modern)",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/LC-1991_237_45_EGDP036526.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/544964",
    "emotionResonance": [
      "resignación"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 85,
      "clarity": 42,
      "intimacy": 72,
      "control": 38
    },
    "description": "Gift of Mr. and Mrs. Jonathan P. Rosen, 1991",
    "poeticDescription": "Relief with offerings and bowing officials"
  },
  {
    "id": "met-sculpt-254679",
    "title": "Carnelian scaraboid seal",
    "artist": "Anonymous",
    "year": "ca. 450–430 BCE",
    "medium": "Carnelian",
    "culture": "Greek",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP142925.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/254679",
    "emotionResonance": [
      "resignación"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "herakles"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 85,
      "clarity": 42,
      "intimacy": 72,
      "control": 38
    },
    "description": "Rogers Fund, 1951",
    "poeticDescription": "Carnelian scaraboid seal"
  },
  {
    "id": "met-sculpt-249149",
    "title": "Gold swivel ring with banded agate scarab",
    "artist": "Anonymous",
    "year": "4th century BCE",
    "medium": "Agate, banded, gold",
    "culture": "Etruscan",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/sf1617438.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/249149",
    "emotionResonance": [
      "resignación"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men"
    ],
    "resonance": {
      "energy": 22,
      "temperature": 32,
      "tension": 48,
      "density": 72,
      "movement": 22,
      "temporality": 88,
      "humanity": 85,
      "clarity": 42,
      "intimacy": 72,
      "control": 38
    },
    "description": "Rogers Fund, 1916",
    "poeticDescription": "Gold swivel ring with banded agate scarab"
  },
  {
    "id": "met-sculpt-248675",
    "title": "Bronze grotesque",
    "artist": "Anonymous",
    "year": "2nd century BCE–1st century CE",
    "medium": "Bronze",
    "culture": "Greek",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP116957.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/248675",
    "emotionResonance": [
      "asco"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "men"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 28,
      "tension": 85,
      "density": 78,
      "movement": 45,
      "temporality": 18,
      "humanity": 32,
      "clarity": 58,
      "intimacy": 22,
      "control": 42
    },
    "description": "Rogers Fund, 1912",
    "poeticDescription": "Bronze grotesque"
  },
  {
    "id": "met-sculpt-472243",
    "title": "Double Capital",
    "artist": "Anonymous",
    "year": "late 15th century",
    "medium": "Marble",
    "culture": "French",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/cl/web-large/cds25-120-165.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/472243",
    "emotionResonance": [
      "asco"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 42,
      "temperature": 28,
      "tension": 85,
      "density": 78,
      "movement": 45,
      "temporality": 18,
      "humanity": 32,
      "clarity": 58,
      "intimacy": 22,
      "control": 42
    },
    "description": "The Cloisters Collection, 1925",
    "poeticDescription": "Double Capital"
  },
  {
    "id": "met-sculpt-247892",
    "title": "Terracotta statuette of a man",
    "artist": "Anonymous",
    "year": "2nd–1st century BCE",
    "medium": "Terracotta",
    "culture": "Greek, probably Asia Minor",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP134921.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/247892",
    "emotionResonance": [
      "vergüenza"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "male nudes"
    ],
    "resonance": {
      "energy": 35,
      "temperature": 48,
      "tension": 72,
      "density": 58,
      "movement": 18,
      "temporality": 58,
      "humanity": 82,
      "clarity": 32,
      "intimacy": 52,
      "control": 32
    },
    "description": "Rogers Fund, 1907",
    "poeticDescription": "Terracotta statuette of a man"
  },
  {
    "id": "met-sculpt-257521",
    "title": "Terracotta statuette of a mime with a shield",
    "artist": "Anonymous",
    "year": "2nd–1st century BCE",
    "medium": "Terracotta",
    "culture": "Greek",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/gr/web-large/DP263130.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/257521",
    "emotionResonance": [
      "asco"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "shields",
      "men"
    ],
    "resonance": {
      "energy": 42,
      "temperature": 28,
      "tension": 85,
      "density": 78,
      "movement": 45,
      "temporality": 18,
      "humanity": 32,
      "clarity": 58,
      "intimacy": 22,
      "control": 42
    },
    "description": "Gift of Gordian Weber, 2000",
    "poeticDescription": "Terracotta statuette of a mime with a shield"
  },
  {
    "id": "met-sculpt-24860",
    "title": "Rapier of Prince-Elector Christian II of Saxony (1583–1611)",
    "artist": "Israel Schuech",
    "year": "dated 1606",
    "medium": "Steel, bronze, gold, enamel, paste jewels, cameos, pearls, wood",
    "culture": "hilt, German, Dresden; blade, Spanish, Toledo",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/aa/web-large/LC-1970_77-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/24860",
    "emotionResonance": [
      "esperanza"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 48,
      "temperature": 65,
      "tension": 32,
      "density": 28,
      "movement": 42,
      "temporality": 45,
      "humanity": 88,
      "clarity": 68,
      "intimacy": 58,
      "control": 48
    },
    "description": "Fletcher Fund, 1970",
    "poeticDescription": "Rapier of Prince-Elector Christian II of Saxony (1583–1611)"
  },
  {
    "id": "met-sculpt-470771",
    "title": "Relief of  Agnus Dei and Cherub",
    "artist": "Anonymous",
    "year": "ca. 1140–50",
    "medium": "Marble",
    "culture": "Catalan",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/cl/web-large/LC-25_120_574.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/470771",
    "emotionResonance": [
      "alegría"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "putti",
      "lambs"
    ],
    "resonance": {
      "energy": 75,
      "temperature": 78,
      "tension": 20,
      "density": 35,
      "movement": 80,
      "temporality": 45,
      "humanity": 82,
      "clarity": 78,
      "intimacy": 65,
      "control": 55
    },
    "description": "The Cloisters Collection, 1925",
    "poeticDescription": "Relief of  Agnus Dei and Cherub"
  },
  {
    "id": "met-sculpt-307654",
    "title": "Cherub (?)",
    "artist": "Anonymous",
    "year": "17th century (?)",
    "medium": "Andesite, remains of plaster",
    "culture": "Colonial",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/ao/web-large/DP104846.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/307654",
    "emotionResonance": [
      "alegría"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "human figures"
    ],
    "resonance": {
      "energy": 75,
      "temperature": 78,
      "tension": 20,
      "density": 35,
      "movement": 80,
      "temporality": 45,
      "humanity": 82,
      "clarity": 78,
      "intimacy": 65,
      "control": 55
    },
    "description": "Museum Purchase, 1900",
    "poeticDescription": "Cherub (?)"
  },
  {
    "id": "met-sculpt-202237",
    "title": "Cherub and shell",
    "artist": "Sculptor close to Donatello",
    "year": "possibly 1470s",
    "medium": "Bronze",
    "culture": "Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-1368-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/202237",
    "emotionResonance": [
      "alegría"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "putti"
    ],
    "resonance": {
      "energy": 75,
      "temperature": 78,
      "tension": 20,
      "density": 35,
      "movement": 80,
      "temporality": 45,
      "humanity": 82,
      "clarity": 78,
      "intimacy": 65,
      "control": 55
    },
    "description": "Gift of Alastair Bradley Martin, 1958",
    "poeticDescription": "Cherub and shell"
  },
  {
    "id": "met-sculpt-206287",
    "title": "Head of a cherub",
    "artist": "Anonymous",
    "year": "mid-18th century",
    "medium": "Polychromed wood",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/204924.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/206287",
    "emotionResonance": [
      "admiración",
      "alegría"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "heads",
      "angels"
    ],
    "resonance": {
      "energy": 64,
      "temperature": 70,
      "tension": 24,
      "density": 39,
      "movement": 59,
      "temporality": 52,
      "humanity": 81,
      "clarity": 75,
      "intimacy": 60,
      "control": 54
    },
    "description": "The Lesley and Emma Sheafer Collection, Bequest of Emma A. Sheafer, 1973",
    "poeticDescription": "Head of a cherub"
  },
  {
    "id": "met-sculpt-206996",
    "title": "Satyr",
    "artist": "Antico (Pier Jacopo Alari Bonacolsi)",
    "year": "ca. 1510–ca. 1520",
    "medium": "Bronze, with remains of dark brown lacquer",
    "culture": "Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-612-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/206996",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "satyrs"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "The Jack and Belle Linsky Collection, 1982",
    "poeticDescription": "Satyr"
  },
  {
    "id": "met-sculpt-461462",
    "title": "Satyr",
    "artist": "Desiderio da Firenze",
    "year": "ca. 1530",
    "medium": "Copper alloy with a reddish brown patina; the base and shell with a dark brown patina.",
    "culture": "Italian",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/rl/web-large/SF-1975-1-1395.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/461462",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "satyrs"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "Robert Lehman Collection, 1975",
    "poeticDescription": "Satyr"
  },
  {
    "id": "met-sculpt-191830",
    "title": "Satyr",
    "artist": "Wedgwood and Bentley",
    "year": "1769–80",
    "medium": "Jasper ware",
    "culture": "British",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/DP-15822-035.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/191830",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "satyrs",
      "trees"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "Rogers Fund, 1911",
    "poeticDescription": "Satyr"
  },
  {
    "id": "met-sculpt-195114",
    "title": "Satyr",
    "artist": "Anonymous",
    "year": "17th century",
    "medium": "Ivory",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/es/web-large/56748.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/195114",
    "emotionResonance": [
      "humor"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "satyrs"
    ],
    "resonance": {
      "energy": 68,
      "temperature": 72,
      "tension": 28,
      "density": 42,
      "movement": 72,
      "temporality": 28,
      "humanity": 68,
      "clarity": 82,
      "intimacy": 52,
      "control": 58
    },
    "description": "Bequest of Mary Clark Thompson, 1923",
    "poeticDescription": "Satyr"
  },
  {
    "id": "met-sculpt-553647",
    "title": "Lower half of a goddess on a throne with Bes figures, its base formed by prostrate captives",
    "artist": "Anonymous",
    "year": "ca. 1295–1070 B.C.",
    "medium": "Faience",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/LC-1976_228_EGDP028852.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/553647",
    "emotionResonance": [
      "sublimidad",
      "soberbia"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 68,
      "temperature": 57,
      "tension": 44,
      "density": 44,
      "movement": 42,
      "temporality": 65,
      "humanity": 39,
      "clarity": 60,
      "intimacy": 25,
      "control": 54
    },
    "description": "Purchase, Rogers Fund and William Kemble Gift, 1976",
    "poeticDescription": "Lower half of a goddess on a throne with Bes figures, its base formed by prostrate captives"
  },
  {
    "id": "met-sculpt-576660",
    "title": "Relief fragment with feather pattern",
    "artist": "Anonymous",
    "year": "ca. 2040–1300 B.C.",
    "medium": "Limestone, paint",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/DP-37738-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/576660",
    "emotionResonance": [
      "soberbia"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 68,
      "temperature": 62,
      "tension": 32,
      "density": 42,
      "movement": 42,
      "temporality": 42,
      "humanity": 22,
      "clarity": 78,
      "intimacy": 22,
      "control": 72
    },
    "description": "Gift of James H. Schwartz, 2006 (2006.82.1)\r\nMuseum Accession (X.631.3)",
    "poeticDescription": "Relief fragment with feather pattern"
  },
  {
    "id": "met-sculpt-38285",
    "title": "Seated Transcendent Buddha Vairochana",
    "artist": "Anonymous",
    "year": "ca. second half of the 10th century",
    "medium": "Buddha: silver;  pedestal and throne back: bronze",
    "culture": "Indonesia (Java)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/1987_142_13.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38285",
    "emotionResonance": [
      "trascendencia",
      "serenidad",
      "soberbia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "buddhism",
      "buddha"
    ],
    "resonance": {
      "energy": 52,
      "temperature": 55,
      "tension": 23,
      "density": 38,
      "movement": 42,
      "temporality": 48,
      "humanity": 55,
      "clarity": 80,
      "intimacy": 50,
      "control": 71
    },
    "description": "Samuel Eilenberg Collection, Gift of Samuel Eilenberg, 1987",
    "poeticDescription": "Seated Transcendent Buddha Vairochana"
  },
  {
    "id": "met-sculpt-546016",
    "title": "Fragment of statue of Thutmose III",
    "artist": "Anonymous",
    "year": "ca. 1479–1425 B.C.",
    "medium": "Grey Schist",
    "culture": "—",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/eg/web-large/LC-50_19_1_EGDP029830.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/546016",
    "emotionResonance": [
      "soberbia"
    ],
    "colorResonance": [],
    "atmosphereTags": [],
    "resonance": {
      "energy": 68,
      "temperature": 62,
      "tension": 32,
      "density": 42,
      "movement": 42,
      "temporality": 42,
      "humanity": 22,
      "clarity": 78,
      "intimacy": 22,
      "control": 72
    },
    "description": "Gift of Mrs. Morton C. Nichols, 1950",
    "poeticDescription": "Fragment of statue of Thutmose III"
  },
  {
    "id": "met-sculpt-38341",
    "title": "Durga as Slayer of the Buffalo Demon Mahishasura",
    "artist": "Anonymous",
    "year": "14th–15th century",
    "medium": "Gilt copper alloy, inlaid with semiprecious stones",
    "culture": "Nepal",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DT5236.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38341",
    "emotionResonance": [
      "sublimidad",
      "fobia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "goddess",
      "durga"
    ],
    "resonance": {
      "energy": 75,
      "temperature": 37,
      "tension": 74,
      "density": 59,
      "movement": 55,
      "temporality": 55,
      "humanity": 57,
      "clarity": 42,
      "intimacy": 32,
      "control": 29
    },
    "description": "Gift of Alice and Nasli M. Heeramaneck, 1986",
    "poeticDescription": "Durga as Slayer of the Buffalo Demon Mahishasura"
  },
  {
    "id": "met-sculpt-38511",
    "title": "Krishna Killing the Horse Demon Keshi",
    "artist": "Anonymous",
    "year": "5th century",
    "medium": "Terracotta",
    "culture": "India (Uttar Pradesh)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DT5237.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/38511",
    "emotionResonance": [
      "fobia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "gupta",
      "horses",
      "demons",
      "krishna"
    ],
    "resonance": {
      "energy": 82,
      "temperature": 22,
      "tension": 92,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 22
    },
    "description": "Purchase, Florence and Herbert Irving Gift, 1991",
    "poeticDescription": "Krishna Killing the Horse Demon Keshi"
  },
  {
    "id": "met-sculpt-844987",
    "title": "Goddess Durga slaying the demon Mahisha",
    "artist": "Anonymous",
    "year": "ca. 12th century",
    "medium": "Copper alloy",
    "culture": "Bangladesh, northern Bengal, possibly Varendra region",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP-20872-001.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/844987",
    "emotionResonance": [
      "sublimidad",
      "fobia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "durga"
    ],
    "resonance": {
      "energy": 75,
      "temperature": 37,
      "tension": 74,
      "density": 59,
      "movement": 55,
      "temporality": 55,
      "humanity": 57,
      "clarity": 42,
      "intimacy": 32,
      "control": 29
    },
    "description": "Purchase, David Nalin Gift, The Miriam and Ira D. Wallach Foundation and Richard Greenbaum Funds, and Florence and Herbert Irving Acquisitions Fund for Asian Art, 2020",
    "poeticDescription": "Goddess Durga slaying the demon Mahisha"
  },
  {
    "id": "met-sculpt-39221",
    "title": "Palanquin Ring with Demon Battling a Horse",
    "artist": "Anonymous",
    "year": "ca. early 13th century",
    "medium": "Bronze",
    "culture": "Thailand (or Cambodia?)",
    "location": "The Metropolitan Museum of Art, New York",
    "imageUrl": "https://images.metmuseum.org/CRDImages/as/web-large/DP145422.jpg",
    "sourceUrl": "https://www.metmuseum.org/art/collection/search/39221",
    "emotionResonance": [
      "fobia"
    ],
    "colorResonance": [],
    "atmosphereTags": [
      "horses",
      "demons"
    ],
    "resonance": {
      "energy": 82,
      "temperature": 22,
      "tension": 92,
      "density": 72,
      "movement": 68,
      "temporality": 22,
      "humanity": 58,
      "clarity": 42,
      "intimacy": 35,
      "control": 22
    },
    "description": "Purchase, Beningson Family Gift, in honor of Martin Lerner, 1994",
    "poeticDescription": "Palanquin Ring with Demon Battling a Horse"
  }
];
